name: Yarn install
description: 'Run yarn install with node_modules linker and cache enabled'
runs:
  using: composite
  steps:
    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-path
      run: echo "yarn_cache_path=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-path.outputs.yarn_cache_path }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

    - name: Install dependencies
      shell: bash
      run: yarn install
