import { clsx } from 'clsx';
import type { ForwardedRef, ForwardRefExoticComponent, ReactElement, RefAttributes } from 'react';
import { Children, cloneElement, forwardRef, isValidElement, useId, useMemo } from 'react';

import { IconButton } from '../icon-button';
import type { TextInputInternalProps, TextInputProps } from './text-input.types';
import { TextInputCompoundContext } from './text-input-context';
import type { TextInputErrorMessageProps } from './text-input-error-message';
import { TextInputErrorMessage } from './text-input-error-message';
import type { TextInputHelperMessageProps } from './text-input-helper-message';
import { TextInputHelperMessage } from './text-input-helper-message';

type TextInputComponent = ForwardRefExoticComponent<TextInputProps & RefAttributes<HTMLInputElement>> & {
  HelperMessage: typeof TextInputHelperMessage;
  ErrorMessage: typeof TextInputErrorMessage;
};

type TextInputInternalComponent = ForwardRefExoticComponent<
  TextInputInternalProps & RefAttributes<HTMLInputElement>
> & {
  HelperMessage: typeof TextInputHelperMessage;
  ErrorMessage: typeof TextInputErrorMessage;
};

function TextInputInner(
  {
    size = 'medium',
    variant = 'outline',
    isError = false,
    disabled = false,
    onClickClearButton,
    after,
    before,
    frameRef,
    children,
    ...props
  }: TextInputInternalProps,
  ref: ForwardedRef<HTMLInputElement>,
) {
  const autoGeneratedId = useId();
  const { className: _className, ...restInputProps } = props as typeof props & {
    className?: string;
  };
  const inputPropsForContext = useMemo(
    () => ({
      ...restInputProps,
      size,
      isError,
      disabled,
      onClickClearButton,
      after,
    }),
    [restInputProps, size, isError, disabled, onClickClearButton, after],
  );

  const contextValue = useMemo(
    () => ({
      inputProps: inputPropsForContext,
      forwardedRef: ref,
    }),
    [inputPropsForContext, ref],
  );

  const helperMessageIds: string[] = [];
  const errorIds: string[] = [];
  const describedByBaseId = restInputProps.id ?? autoGeneratedId;

  const enhancedChildren = Children.map(children, (child) => {
    if (!isValidElement(child)) {
      return child;
    }

    if (child.type === TextInputHelperMessage) {
      const helperChild = child as ReactElement<TextInputHelperMessageProps>;
      const assignedId = helperChild.props.id ?? `${describedByBaseId}-helper-${helperMessageIds.length + 1}`;
      helperMessageIds.push(assignedId);

      return cloneElement(helperChild, { id: assignedId });
    }

    if (child.type === TextInputErrorMessage && isError) {
      const errorChild = child as ReactElement<TextInputErrorMessageProps>;
      const assignedId = errorChild.props.id ?? `${describedByBaseId}-error-${errorIds.length + 1}`;
      errorIds.push(assignedId);

      return cloneElement(errorChild, { id: assignedId });
    }

    return child;
  });

  const describedByFromProps =
    typeof restInputProps['aria-describedby'] === 'string' ? restInputProps['aria-describedby'] : null;
  const describedByList = [describedByFromProps, ...helperMessageIds, ...errorIds].filter(
    (id): id is string => typeof id === 'string' && id.trim().length > 0,
  );
  const describedByProps =
    describedByList.length > 0
      ? {
          'aria-describedby': describedByList.join(' '),
        }
      : {};

  const shouldMarkInvalid = isError === true || errorIds.length > 0;
  const ariaInvalidFromProps = restInputProps['aria-invalid'];
  const ariaInvalidValue = ariaInvalidFromProps != null ? ariaInvalidFromProps : shouldMarkInvalid ? true : null;
  const ariaInvalidProps = ariaInvalidValue == null ? {} : { 'aria-invalid': ariaInvalidValue };

  const mergedInputProps = {
    ...restInputProps,
    ...describedByProps,
    ...ariaInvalidProps,
    disabled,
  };

  const isShowClearButton = !!onClickClearButton && restInputProps.value.length !== 0 && !disabled;
  const hasTrailingElement = isShowClearButton || after != null;

  const isBorderless = variant === 'text';

  const inputWrapClasses = clsx('relative flex items-center gap-2 overflow-hidden rounded border', {
    // outline variant
    'border-uiBorder02': !isBorderless && !isError && !disabled,
    'border-supportError': !isBorderless && isError && !disabled,
    'hover:border-hoverInput': !isBorderless && !disabled && !isError,
    'hover:focus-within:border-activeInput': !isBorderless && !isError,
    'focus-within:border-activeInput': !isBorderless && !isError,
    'bg-disabled02 border-disabled01': !isBorderless && disabled,
    // text variant
    'border-transparent': isBorderless,
    // 共通
    'bg-uiBackground01': !disabled || isBorderless,
    'pr-2': !isBorderless && size === 'medium' && hasTrailingElement,
    'pr-3': !isBorderless && (size === 'large' || size === 'x-large') && hasTrailingElement,
  });

  // input の文字まわり（typography・文字色・placeholder 色・disabled 色）。
  // before 有無の 2 つの input で共有し、見た目がモードで食い違わないようにする。
  const inputTextClassMap = {
    'disabled:text-textPlaceholder': !isBorderless,
    'disabled:text-disabled01': isBorderless,
    'typography-label14regular': size === 'medium',
    'typography-label16regular': size === 'large' || size === 'x-large',
    // テキスト色
    'text-text01': !isError,
    'text-supportError': isError,
    // placeholder 色（text variant エラー時のみ上書き）
    'placeholder:text-textPlaceholder': !(isBorderless && isError && !disabled),
    'placeholder:text-supportErrorLight': isBorderless && isError && !disabled,
  };

  const inputClasses = clsx('flex-1 bg-transparent outline-none', inputTextClassMap, {
    // 高さ
    'min-h-8': size === 'medium',
    'min-h-10': size === 'large',
    'min-h-12': size === 'x-large',
    // outline: 従来の padding / text: padding なし
    'px-2': !isBorderless && size === 'medium',
    'px-3': !isBorderless && (size === 'large' || size === 'x-large'),
    'pr-0': hasTrailingElement,
  });

  // before 指定時のみ使う: 折り返しコンテナに min-h / padding を移し、input は残り幅を埋める。
  const hasBefore = before != null;

  // 上下の padding は、1 行のとき（min-h の中で items-center により中央揃え）と同じ値にする。
  // 共通の値（例: py-1）にすると、折り返して min-h を超えたときに先頭の行の上の隙間だけが狭くなるため。
  // 例: medium は (32px - 行の高さ 20px) / 2 = 6px（py-1.5）
  const beforeContainerClasses = clsx('flex min-w-0 flex-1 flex-wrap items-center gap-1', {
    'min-h-8 py-1.5': size === 'medium',
    'min-h-10 py-2.5': size === 'large',
    'min-h-12 py-3.5': size === 'x-large',
    'px-2': !isBorderless && size === 'medium',
    'px-3': !isBorderless && (size === 'large' || size === 'x-large'),
    'pr-0': hasTrailingElement,
  });

  const inputInBeforeContainerClasses = clsx('min-w-20 flex-1 bg-transparent outline-none', inputTextClassMap);

  // before 指定時のみ使う: 末尾の要素（after・クリアボタン）を 1 行の高さの箱に入れて枠の下端に揃える。
  // 1 行のときは従来どおり縦中央、折り返して複数行になったときは input のある最後の行の横に並ぶ
  // （最後の行の中心は下から「上下 padding + 行の高さ / 2」＝ 1 行の高さ / 2 の位置にあるため）。
  const beforeTrailingClasses = clsx('flex shrink-0 items-center gap-2 self-end', {
    'min-h-8': size === 'medium',
    'min-h-10': size === 'large',
    'min-h-12': size === 'x-large',
  });

  const inputElement = (
    <div ref={frameRef} className={inputWrapClasses}>
      {hasBefore ? (
        <div className={beforeContainerClasses}>
          {before}
          <input ref={ref} size={1} className={inputInBeforeContainerClasses} {...mergedInputProps} />
        </div>
      ) : (
        <input ref={ref} size={1} className={inputClasses} {...mergedInputProps} />
      )}
      {hasBefore ? (
        hasTrailingElement && (
          <div className={beforeTrailingClasses}>
            {after}
            {isShowClearButton && <IconButton variant="text" icon="close" size="small" onClick={onClickClearButton} />}
          </div>
        )
      ) : (
        <>
          {after}
          {isShowClearButton && <IconButton variant="text" icon="close" size="small" onClick={onClickClearButton} />}
        </>
      )}
    </div>
  );

  const stackedChildren = enhancedChildren == null ? [] : Children.toArray(enhancedChildren);
  const hasMessageChildren = stackedChildren.length > 0;

  if (!hasMessageChildren) {
    return <TextInputCompoundContext.Provider value={contextValue}>{inputElement}</TextInputCompoundContext.Provider>;
  }

  return (
    <TextInputCompoundContext.Provider value={contextValue}>
      <div className="flex flex-col gap-2">
        {inputElement}
        {stackedChildren}
      </div>
    </TextInputCompoundContext.Provider>
  );
}

const attachStatics = <T extends TextInputComponent | TextInputInternalComponent>(component: T): T => {
  component.HelperMessage = TextInputHelperMessage;
  component.ErrorMessage = TextInputErrorMessage;
  component.displayName = 'TextInput';

  return component;
};

const TextInputPublic = forwardRef<HTMLInputElement, TextInputProps>(function TextInputPublic(props, ref) {
  return TextInputInner(props as TextInputInternalProps, ref);
}) as TextInputComponent;

const InternalTextInputBase = forwardRef<HTMLInputElement, TextInputInternalProps>(
  function InternalTextInputBase(props, ref) {
    return TextInputInner(props, ref);
  },
) as TextInputInternalComponent;

const TextInput = attachStatics(TextInputPublic);
const InternalTextInput = attachStatics(InternalTextInputBase);

export { InternalTextInput, TextInput };
