nodeLinker: node-modules

npmScopes:
  zenkigen-inc:
    npmAuthToken: '${NODE_AUTH_TOKEN-}'

yarnPath: .yarn/releases/yarn-4.9.2.cjs

packageExtensions:
  '@modelcontextprotocol/inspector@*':
    dependencies:
      commander: '^13.1.0'
