nodeLinker: node-modules

npmScopes:
  zenkigen-inc:
    npmAuthToken: '${NODE_AUTH_TOKEN-}'
    npmRegistryServer: '${NPM_REGISTRY_URL-https://registry.npmjs.org}'

yarnPath: .yarn/releases/yarn-4.9.2.cjs
