/*
* NOTE: This class is auto generated by /zenkigen/workplace-frontend/packages/component-icon
* Do not edit the class manually.
*/
import type React from 'react';

export type IconName = 'warning' | 'volume' | 'volume-off' | 'video' | 'user' | 'user-remove' | 'user-photograph' | 'user-one' | 'user-multi' | 'user-line' | 'user-group' | 'user-add' | 'upload' | 'triangle' | 'transcription' | 'timer' | 'table' | 'table-upload' | 'table-download' | 'success-filled' | 'store' | 'star' | 'star-filled' | 'sparkle' | 'sort' | 'sort-up' | 'sort-down' | 'slider-editing' | 'sidebar' | 'shuffle' | 'share' | 'send' | 'search' | 'score' | 'remove' | 'presentation' | 'play' | 'play-filled' | 'picture-in-picture' | 'pdf' | 'pause' | 'notification' | 'movie' | 'more' | 'message-text' | 'logout' | 'list' | 'link' | 'input-delete' | 'information' | 'information-filled' | 'image' | 'home' | 'hint' | 'help' | 'hamburger' | 'hamburger-close' | 'graph-line' | 'global' | 'flag' | 'filter' | 'external-link' | 'expand' | 'email' | 'edit' | 'download' | 'download-document' | 'double circle' | 'documents' | 'document' | 'delete' | 'copy' | 'contract' | 'comment' | 'close' | 'circle' | 'check' | 'chart-line' | 'chart-bar' | 'caret-right' | 'caret-down' | 'calendar' | 'calendar-today' | 'calendar-minus' | 'calendar-draft' | 'calendar-check' | 'building' | 'attention' | 'attachment' | 'arrow-up' | 'arrow-right' | 'arrow-left' | 'arrow-down' | 'angle-up' | 'angle-small-up' | 'angle-small-down' | 'angle-right' | 'angle-left' | 'angle-down' | 'ai' | 'add';

export type IconElements = Readonly<{ [name in IconName]: React.ReactElement }>;

// Import all icon components

import { addIcon } from './icons/add';
import { aiIcon } from './icons/ai';
import { angledownIcon } from './icons/angle-down';
import { angleleftIcon } from './icons/angle-left';
import { anglerightIcon } from './icons/angle-right';
import { anglesmalldownIcon } from './icons/angle-small-down';
import { anglesmallupIcon } from './icons/angle-small-up';
import { angleupIcon } from './icons/angle-up';
import { arrowdownIcon } from './icons/arrow-down';
import { arrowleftIcon } from './icons/arrow-left';
import { arrowrightIcon } from './icons/arrow-right';
import { arrowupIcon } from './icons/arrow-up';
import { attachmentIcon } from './icons/attachment';
import { attentionIcon } from './icons/attention';
import { buildingIcon } from './icons/building';
import { calendarIcon } from './icons/calendar';
import { calendarcheckIcon } from './icons/calendar-check';
import { calendardraftIcon } from './icons/calendar-draft';
import { calendarminusIcon } from './icons/calendar-minus';
import { calendartodayIcon } from './icons/calendar-today';
import { caretdownIcon } from './icons/caret-down';
import { caretrightIcon } from './icons/caret-right';
import { chartbarIcon } from './icons/chart-bar';
import { chartlineIcon } from './icons/chart-line';
import { checkIcon } from './icons/check';
import { circleIcon } from './icons/circle';
import { closeIcon } from './icons/close';
import { commentIcon } from './icons/comment';
import { contractIcon } from './icons/contract';
import { copyIcon } from './icons/copy';
import { deleteIcon } from './icons/delete';
import { documentIcon } from './icons/document';
import { documentsIcon } from './icons/documents';
import { doublecircleIcon } from './icons/double circle';
import { downloadIcon } from './icons/download';
import { downloaddocumentIcon } from './icons/download-document';
import { editIcon } from './icons/edit';
import { emailIcon } from './icons/email';
import { expandIcon } from './icons/expand';
import { externallinkIcon } from './icons/external-link';
import { filterIcon } from './icons/filter';
import { flagIcon } from './icons/flag';
import { globalIcon } from './icons/global';
import { graphlineIcon } from './icons/graph-line';
import { hamburgerIcon } from './icons/hamburger';
import { hamburgercloseIcon } from './icons/hamburger-close';
import { helpIcon } from './icons/help';
import { hintIcon } from './icons/hint';
import { homeIcon } from './icons/home';
import { imageIcon } from './icons/image';
import { informationIcon } from './icons/information';
import { informationfilledIcon } from './icons/information-filled';
import { inputdeleteIcon } from './icons/input-delete';
import { linkIcon } from './icons/link';
import { listIcon } from './icons/list';
import { logoutIcon } from './icons/logout';
import { messagetextIcon } from './icons/message-text';
import { moreIcon } from './icons/more';
import { movieIcon } from './icons/movie';
import { notificationIcon } from './icons/notification';
import { pauseIcon } from './icons/pause';
import { pdfIcon } from './icons/pdf';
import { pictureinpictureIcon } from './icons/picture-in-picture';
import { playIcon } from './icons/play';
import { playfilledIcon } from './icons/play-filled';
import { presentationIcon } from './icons/presentation';
import { removeIcon } from './icons/remove';
import { scoreIcon } from './icons/score';
import { searchIcon } from './icons/search';
import { sendIcon } from './icons/send';
import { shareIcon } from './icons/share';
import { shuffleIcon } from './icons/shuffle';
import { sidebarIcon } from './icons/sidebar';
import { slidereditingIcon } from './icons/slider-editing';
import { sortIcon } from './icons/sort';
import { sortdownIcon } from './icons/sort-down';
import { sortupIcon } from './icons/sort-up';
import { sparkleIcon } from './icons/sparkle';
import { starIcon } from './icons/star';
import { starfilledIcon } from './icons/star-filled';
import { storeIcon } from './icons/store';
import { successfilledIcon } from './icons/success-filled';
import { tableIcon } from './icons/table';
import { tabledownloadIcon } from './icons/table-download';
import { tableuploadIcon } from './icons/table-upload';
import { timerIcon } from './icons/timer';
import { transcriptionIcon } from './icons/transcription';
import { triangleIcon } from './icons/triangle';
import { uploadIcon } from './icons/upload';
import { userIcon } from './icons/user';
import { useraddIcon } from './icons/user-add';
import { usergroupIcon } from './icons/user-group';
import { userlineIcon } from './icons/user-line';
import { usermultiIcon } from './icons/user-multi';
import { useroneIcon } from './icons/user-one';
import { userphotographIcon } from './icons/user-photograph';
import { userremoveIcon } from './icons/user-remove';
import { videoIcon } from './icons/video';
import { volumeIcon } from './icons/volume';
import { volumeoffIcon } from './icons/volume-off';
import { warningIcon } from './icons/warning';


// Icon elements mapping
export const iconElements: IconElements = {
  
    'warning': warningIcon,
  
    'volume': volumeIcon,
  
    'volume-off': volumeoffIcon,
  
    'video': videoIcon,
  
    'user': userIcon,
  
    'user-remove': userremoveIcon,
  
    'user-photograph': userphotographIcon,
  
    'user-one': useroneIcon,
  
    'user-multi': usermultiIcon,
  
    'user-line': userlineIcon,
  
    'user-group': usergroupIcon,
  
    'user-add': useraddIcon,
  
    'upload': uploadIcon,
  
    'triangle': triangleIcon,
  
    'transcription': transcriptionIcon,
  
    'timer': timerIcon,
  
    'table': tableIcon,
  
    'table-upload': tableuploadIcon,
  
    'table-download': tabledownloadIcon,
  
    'success-filled': successfilledIcon,
  
    'store': storeIcon,
  
    'star': starIcon,
  
    'star-filled': starfilledIcon,
  
    'sparkle': sparkleIcon,
  
    'sort': sortIcon,
  
    'sort-up': sortupIcon,
  
    'sort-down': sortdownIcon,
  
    'slider-editing': slidereditingIcon,
  
    'sidebar': sidebarIcon,
  
    'shuffle': shuffleIcon,
  
    'share': shareIcon,
  
    'send': sendIcon,
  
    'search': searchIcon,
  
    'score': scoreIcon,
  
    'remove': removeIcon,
  
    'presentation': presentationIcon,
  
    'play': playIcon,
  
    'play-filled': playfilledIcon,
  
    'picture-in-picture': pictureinpictureIcon,
  
    'pdf': pdfIcon,
  
    'pause': pauseIcon,
  
    'notification': notificationIcon,
  
    'movie': movieIcon,
  
    'more': moreIcon,
  
    'message-text': messagetextIcon,
  
    'logout': logoutIcon,
  
    'list': listIcon,
  
    'link': linkIcon,
  
    'input-delete': inputdeleteIcon,
  
    'information': informationIcon,
  
    'information-filled': informationfilledIcon,
  
    'image': imageIcon,
  
    'home': homeIcon,
  
    'hint': hintIcon,
  
    'help': helpIcon,
  
    'hamburger': hamburgerIcon,
  
    'hamburger-close': hamburgercloseIcon,
  
    'graph-line': graphlineIcon,
  
    'global': globalIcon,
  
    'flag': flagIcon,
  
    'filter': filterIcon,
  
    'external-link': externallinkIcon,
  
    'expand': expandIcon,
  
    'email': emailIcon,
  
    'edit': editIcon,
  
    'download': downloadIcon,
  
    'download-document': downloaddocumentIcon,
  
    'double circle': doublecircleIcon,
  
    'documents': documentsIcon,
  
    'document': documentIcon,
  
    'delete': deleteIcon,
  
    'copy': copyIcon,
  
    'contract': contractIcon,
  
    'comment': commentIcon,
  
    'close': closeIcon,
  
    'circle': circleIcon,
  
    'check': checkIcon,
  
    'chart-line': chartlineIcon,
  
    'chart-bar': chartbarIcon,
  
    'caret-right': caretrightIcon,
  
    'caret-down': caretdownIcon,
  
    'calendar': calendarIcon,
  
    'calendar-today': calendartodayIcon,
  
    'calendar-minus': calendarminusIcon,
  
    'calendar-draft': calendardraftIcon,
  
    'calendar-check': calendarcheckIcon,
  
    'building': buildingIcon,
  
    'attention': attentionIcon,
  
    'attachment': attachmentIcon,
  
    'arrow-up': arrowupIcon,
  
    'arrow-right': arrowrightIcon,
  
    'arrow-left': arrowleftIcon,
  
    'arrow-down': arrowdownIcon,
  
    'angle-up': angleupIcon,
  
    'angle-small-up': anglesmallupIcon,
  
    'angle-small-down': anglesmalldownIcon,
  
    'angle-right': anglerightIcon,
  
    'angle-left': angleleftIcon,
  
    'angle-down': angledownIcon,
  
    'ai': aiIcon,
  
    'add': addIcon,
  
};
