/*
* NOTE: This class is auto generated by /zenkigen/workplace-frontend/packages/component-icon
* Do not edit the class manually.
*/
import type React from 'react';

export type IconName = 'add' | 'ai-agent' | 'ai' | 'angle-down' | 'angle-left' | 'angle-right' | 'angle-small-down' | 'angle-small-up' | 'angle-up' | 'arrow-down' | 'arrow-left' | 'arrow-right' | 'arrow-up' | 'attachment' | 'attention' | 'background-blur-strong' | 'background-blur-weak' | 'beginner' | 'block' | 'bookmark' | 'building' | 'calendar-attention' | 'calendar-check' | 'calendar-draft' | 'calendar-minus' | 'calendar-today' | 'calendar' | 'caret-down' | 'caret-right' | 'catch' | 'chart-bar' | 'chart-line' | 'check' | 'circle' | 'close' | 'comment' | 'contract' | 'copy' | 'delete' | 'display' | 'document-edit' | 'document' | 'documents' | 'double-circle' | 'download-document' | 'download' | 'edit' | 'email' | 'exit' | 'expand' | 'external-link' | 'feedback' | 'filter' | 'flag' | 'global' | 'graph-line' | 'guide' | 'hamburger-close' | 'hamburger-open' | 'hamburger' | 'handle' | 'harutaka' | 'help' | 'hint' | 'home' | 'image' | 'information-filled' | 'information' | 'input-delete' | 'link' | 'list' | 'live-background' | 'logout' | 'main-view' | 'message-text' | 'mic-off' | 'mic' | 'minus' | 'more' | 'movie' | 'network' | 'notification' | 'pause' | 'pdf' | 'picture-in-picture' | 'play-filled' | 'play' | 'plus' | 'presentation' | 'record' | 'reload' | 'remove' | 'repeat' | 'score' | 'screen-share' | 'search' | 'security' | 'send' | 'setting' | 'share' | 'shuffle' | 'sidebar' | 'signal-low' | 'signal-off' | 'signal' | 'slider-editing' | 'sort-down' | 'sort-up' | 'sort' | 'sparkle' | 'stamp' | 'star-filled' | 'star' | 'success-filled' | 'superadmin' | 'table-download' | 'table-upload' | 'table' | 'timer' | 'transcription' | 'triangle' | 'upload-document-success' | 'upload' | 'user-add' | 'user-group' | 'user-line' | 'user-multi' | 'user-one' | 'user-remove' | 'user-verified' | 'user' | 'video-off' | 'video' | 'visibility-off' | 'visibility' | 'volume-off' | 'volume' | 'warning';

export type IconComponent = React.FC<{ accentClassName?: string }>;

// Import all icon components

import { addIcon } from './icons/add';

import { aiagentIcon } from './icons/ai-agent';

import { aiIcon } from './icons/ai';

import { angledownIcon } from './icons/angle-down';

import { angleleftIcon } from './icons/angle-left';

import { anglerightIcon } from './icons/angle-right';

import { anglesmalldownIcon } from './icons/angle-small-down';

import { anglesmallupIcon } from './icons/angle-small-up';

import { angleupIcon } from './icons/angle-up';

import { arrowdownIcon } from './icons/arrow-down';

import { arrowleftIcon } from './icons/arrow-left';

import { arrowrightIcon } from './icons/arrow-right';

import { arrowupIcon } from './icons/arrow-up';

import { attachmentIcon } from './icons/attachment';

import { attentionIcon } from './icons/attention';

import { backgroundblurstrongIcon } from './icons/background-blur-strong';

import { backgroundblurweakIcon } from './icons/background-blur-weak';

import { beginnerIcon } from './icons/beginner';

import { blockIcon } from './icons/block';

import { bookmarkIcon } from './icons/bookmark';

import { buildingIcon } from './icons/building';

import { calendarattentionIcon } from './icons/calendar-attention';

import { calendarcheckIcon } from './icons/calendar-check';

import { calendardraftIcon } from './icons/calendar-draft';

import { calendarminusIcon } from './icons/calendar-minus';

import { calendartodayIcon } from './icons/calendar-today';

import { calendarIcon } from './icons/calendar';

import { caretdownIcon } from './icons/caret-down';

import { caretrightIcon } from './icons/caret-right';

import { catchIcon } from './icons/catch';

import { chartbarIcon } from './icons/chart-bar';

import { chartlineIcon } from './icons/chart-line';

import { checkIcon } from './icons/check';

import { circleIcon } from './icons/circle';

import { closeIcon } from './icons/close';

import { commentIcon } from './icons/comment';

import { contractIcon } from './icons/contract';

import { copyIcon } from './icons/copy';

import { deleteIcon } from './icons/delete';

import { displayIcon } from './icons/display';

import { documenteditIcon } from './icons/document-edit';

import { documentIcon } from './icons/document';

import { documentsIcon } from './icons/documents';

import { doublecircleIcon } from './icons/double-circle';

import { downloaddocumentIcon } from './icons/download-document';

import { downloadIcon } from './icons/download';

import { editIcon } from './icons/edit';

import { emailIcon } from './icons/email';

import { exitIcon } from './icons/exit';

import { expandIcon } from './icons/expand';

import { externallinkIcon } from './icons/external-link';

import { feedbackIcon } from './icons/feedback';

import { filterIcon } from './icons/filter';

import { flagIcon } from './icons/flag';

import { globalIcon } from './icons/global';

import { graphlineIcon } from './icons/graph-line';

import { guideIcon } from './icons/guide';

import { hamburgercloseIcon } from './icons/hamburger-close';

import { hamburgeropenIcon } from './icons/hamburger-open';

import { hamburgerIcon } from './icons/hamburger';

import { handleIcon } from './icons/handle';

import { harutakaIcon } from './icons/harutaka';

import { helpIcon } from './icons/help';

import { hintIcon } from './icons/hint';

import { homeIcon } from './icons/home';

import { imageIcon } from './icons/image';

import { informationfilledIcon } from './icons/information-filled';

import { informationIcon } from './icons/information';

import { inputdeleteIcon } from './icons/input-delete';

import { linkIcon } from './icons/link';

import { listIcon } from './icons/list';

import { livebackgroundIcon } from './icons/live-background';

import { logoutIcon } from './icons/logout';

import { mainviewIcon } from './icons/main-view';

import { messagetextIcon } from './icons/message-text';

import { micoffIcon } from './icons/mic-off';

import { micIcon } from './icons/mic';

import { minusIcon } from './icons/minus';

import { moreIcon } from './icons/more';

import { movieIcon } from './icons/movie';

import { networkIcon } from './icons/network';

import { notificationIcon } from './icons/notification';

import { pauseIcon } from './icons/pause';

import { pdfIcon } from './icons/pdf';

import { pictureinpictureIcon } from './icons/picture-in-picture';

import { playfilledIcon } from './icons/play-filled';

import { playIcon } from './icons/play';

import { plusIcon } from './icons/plus';

import { presentationIcon } from './icons/presentation';

import { recordIcon } from './icons/record';

import { reloadIcon } from './icons/reload';

import { removeIcon } from './icons/remove';

import { repeatIcon } from './icons/repeat';

import { scoreIcon } from './icons/score';

import { screenshareIcon } from './icons/screen-share';

import { searchIcon } from './icons/search';

import { securityIcon } from './icons/security';

import { sendIcon } from './icons/send';

import { settingIcon } from './icons/setting';

import { shareIcon } from './icons/share';

import { shuffleIcon } from './icons/shuffle';

import { sidebarIcon } from './icons/sidebar';

import { signallowIcon } from './icons/signal-low';

import { signaloffIcon } from './icons/signal-off';

import { signalIcon } from './icons/signal';

import { slidereditingIcon } from './icons/slider-editing';

import { sortdownIcon } from './icons/sort-down';

import { sortupIcon } from './icons/sort-up';

import { sortIcon } from './icons/sort';

import { sparkleIcon } from './icons/sparkle';

import { stampIcon } from './icons/stamp';

import { starfilledIcon } from './icons/star-filled';

import { starIcon } from './icons/star';

import { successfilledIcon } from './icons/success-filled';

import { superadminIcon } from './icons/superadmin';

import { tabledownloadIcon } from './icons/table-download';

import { tableuploadIcon } from './icons/table-upload';

import { tableIcon } from './icons/table';

import { timerIcon } from './icons/timer';

import { transcriptionIcon } from './icons/transcription';

import { triangleIcon } from './icons/triangle';

import { uploaddocumentsuccessIcon } from './icons/upload-document-success';

import { uploadIcon } from './icons/upload';

import { useraddIcon } from './icons/user-add';

import { usergroupIcon } from './icons/user-group';

import { userlineIcon } from './icons/user-line';

import { usermultiIcon } from './icons/user-multi';

import { useroneIcon } from './icons/user-one';

import { userremoveIcon } from './icons/user-remove';

import { userverifiedIcon } from './icons/user-verified';

import { userIcon } from './icons/user';

import { videooffIcon } from './icons/video-off';

import { videoIcon } from './icons/video';

import { visibilityoffIcon } from './icons/visibility-off';

import { visibilityIcon } from './icons/visibility';

import { volumeoffIcon } from './icons/volume-off';

import { volumeIcon } from './icons/volume';

import { warningIcon } from './icons/warning';


// Icon elements mapping
export const iconElements = {
  
    'add': addIcon,
  
    'ai-agent': aiagentIcon,
  
    'ai': aiIcon,
  
    'angle-down': angledownIcon,
  
    'angle-left': angleleftIcon,
  
    'angle-right': anglerightIcon,
  
    'angle-small-down': anglesmalldownIcon,
  
    'angle-small-up': anglesmallupIcon,
  
    'angle-up': angleupIcon,
  
    'arrow-down': arrowdownIcon,
  
    'arrow-left': arrowleftIcon,
  
    'arrow-right': arrowrightIcon,
  
    'arrow-up': arrowupIcon,
  
    'attachment': attachmentIcon,
  
    'attention': attentionIcon,
  
    'background-blur-strong': backgroundblurstrongIcon,
  
    'background-blur-weak': backgroundblurweakIcon,
  
    'beginner': beginnerIcon,
  
    'block': blockIcon,
  
    'bookmark': bookmarkIcon,
  
    'building': buildingIcon,
  
    'calendar-attention': calendarattentionIcon,
  
    'calendar-check': calendarcheckIcon,
  
    'calendar-draft': calendardraftIcon,
  
    'calendar-minus': calendarminusIcon,
  
    'calendar-today': calendartodayIcon,
  
    'calendar': calendarIcon,
  
    'caret-down': caretdownIcon,
  
    'caret-right': caretrightIcon,
  
    'catch': catchIcon,
  
    'chart-bar': chartbarIcon,
  
    'chart-line': chartlineIcon,
  
    'check': checkIcon,
  
    'circle': circleIcon,
  
    'close': closeIcon,
  
    'comment': commentIcon,
  
    'contract': contractIcon,
  
    'copy': copyIcon,
  
    'delete': deleteIcon,
  
    'display': displayIcon,
  
    'document-edit': documenteditIcon,
  
    'document': documentIcon,
  
    'documents': documentsIcon,
  
    'double-circle': doublecircleIcon,
  
    'download-document': downloaddocumentIcon,
  
    'download': downloadIcon,
  
    'edit': editIcon,
  
    'email': emailIcon,
  
    'exit': exitIcon,
  
    'expand': expandIcon,
  
    'external-link': externallinkIcon,
  
    'feedback': feedbackIcon,
  
    'filter': filterIcon,
  
    'flag': flagIcon,
  
    'global': globalIcon,
  
    'graph-line': graphlineIcon,
  
    'guide': guideIcon,
  
    'hamburger-close': hamburgercloseIcon,
  
    'hamburger-open': hamburgeropenIcon,
  
    'hamburger': hamburgerIcon,
  
    'handle': handleIcon,
  
    'harutaka': harutakaIcon,
  
    'help': helpIcon,
  
    'hint': hintIcon,
  
    'home': homeIcon,
  
    'image': imageIcon,
  
    'information-filled': informationfilledIcon,
  
    'information': informationIcon,
  
    'input-delete': inputdeleteIcon,
  
    'link': linkIcon,
  
    'list': listIcon,
  
    'live-background': livebackgroundIcon,
  
    'logout': logoutIcon,
  
    'main-view': mainviewIcon,
  
    'message-text': messagetextIcon,
  
    'mic-off': micoffIcon,
  
    'mic': micIcon,
  
    'minus': minusIcon,
  
    'more': moreIcon,
  
    'movie': movieIcon,
  
    'network': networkIcon,
  
    'notification': notificationIcon,
  
    'pause': pauseIcon,
  
    'pdf': pdfIcon,
  
    'picture-in-picture': pictureinpictureIcon,
  
    'play-filled': playfilledIcon,
  
    'play': playIcon,
  
    'plus': plusIcon,
  
    'presentation': presentationIcon,
  
    'record': recordIcon,
  
    'reload': reloadIcon,
  
    'remove': removeIcon,
  
    'repeat': repeatIcon,
  
    'score': scoreIcon,
  
    'screen-share': screenshareIcon,
  
    'search': searchIcon,
  
    'security': securityIcon,
  
    'send': sendIcon,
  
    'setting': settingIcon,
  
    'share': shareIcon,
  
    'shuffle': shuffleIcon,
  
    'sidebar': sidebarIcon,
  
    'signal-low': signallowIcon,
  
    'signal-off': signaloffIcon,
  
    'signal': signalIcon,
  
    'slider-editing': slidereditingIcon,
  
    'sort-down': sortdownIcon,
  
    'sort-up': sortupIcon,
  
    'sort': sortIcon,
  
    'sparkle': sparkleIcon,
  
    'stamp': stampIcon,
  
    'star-filled': starfilledIcon,
  
    'star': starIcon,
  
    'success-filled': successfilledIcon,
  
    'superadmin': superadminIcon,
  
    'table-download': tabledownloadIcon,
  
    'table-upload': tableuploadIcon,
  
    'table': tableIcon,
  
    'timer': timerIcon,
  
    'transcription': transcriptionIcon,
  
    'triangle': triangleIcon,
  
    'upload-document-success': uploaddocumentsuccessIcon,
  
    'upload': uploadIcon,
  
    'user-add': useraddIcon,
  
    'user-group': usergroupIcon,
  
    'user-line': userlineIcon,
  
    'user-multi': usermultiIcon,
  
    'user-one': useroneIcon,
  
    'user-remove': userremoveIcon,
  
    'user-verified': userverifiedIcon,
  
    'user': userIcon,
  
    'video-off': videooffIcon,
  
    'video': videoIcon,
  
    'visibility-off': visibilityoffIcon,
  
    'visibility': visibilityIcon,
  
    'volume-off': volumeoffIcon,
  
    'volume': volumeIcon,
  
    'warning': warningIcon,
  
};
