import { clsx } from 'clsx';
import type { CSSProperties, ReactElement, ReactNode } from 'react';
import { Children, cloneElement, isValidElement, useId, useMemo } from 'react';

import { Select } from '../select';
import type { SelectOption } from '../select/type';
import type { TimePickerSize } from './time-picker-context';
import { TimePickerCompoundContext } from './time-picker-context';
import type { TimePickerErrorMessageProps } from './time-picker-error-message';
import { TimePickerErrorMessage } from './time-picker-error-message';
import type { MinuteStep, TimeValue } from './time-picker-utils';
import { createHourOption, createMinuteOption, generateHourOptions, generateMinuteOptions } from './time-picker-utils';

/** サイズごとの各 Select の既定幅（px, Figma 実測値） */
const SELECT_WIDTH_BY_SIZE: Record<TimePickerSize, number> = {
  'x-small': 80,
  small: 80,
  medium: 80,
  large: 88,
};

/** 時・分 Select の未選択時プレースホルダー（内部固定） */
const PLACEHOLDER = '--';
/** 時 Select トリガーの aria-label（内部固定） */
const HOUR_ARIA_LABEL = '時';
/** 分 Select トリガーの aria-label（内部固定） */
const MINUTE_ARIA_LABEL = '分';
/** 候補リストの最大高さ（内部固定・約 8 候補分）。時 Select（24 候補）が大きく出過ぎるのを防ぐ */
const OPTION_LIST_MAX_HEIGHT = '264px';

export type TimePickerProps = {
  /** 選択時刻。`hour`・`minute` の両方が `null` の場合は未入力を表す */
  value: TimeValue;
  /** 時刻が変更されたときに呼び出されるコールバック関数。各 Select の変更ごとに新しい値を返す */
  onChange: (value: TimeValue) => void;
  /** コンポーネントのサイズ。内部の `Select` の size に 1:1 でマッピングされる @default 'medium' */
  size?: TimePickerSize;
  /** 分候補の刻み（60 の約数） @default 15 */
  minuteStep?: MinuteStep;
  /** 時候補の刻み（通常 1） @default 1 */
  hourStep?: number;
  /** 選択可能な最小時刻（`"HH:mm"`・inclusive）。範囲外の候補は非表示になる */
  minTime?: string;
  /** 選択可能な最大時刻（`"HH:mm"`・inclusive）。範囲外の候補は非表示になる */
  maxTime?: string;
  /** 無効状態かどうか @default false */
  isDisabled?: boolean;
  /** エラー状態かどうか。`true` の場合、両方の Select がエラー表示になる @default false */
  isError?: boolean;
  /** 全体幅。指定した場合、各 Select が均等に伸長する。省略時は size に応じた固定幅になる */
  width?: CSSProperties['width'];
  /** Compound Component（`TimePicker.ErrorMessage`） */
  children?: ReactNode;
};

type TimePickerComponent = ((props: TimePickerProps) => ReactElement) & {
  ErrorMessage: typeof TimePickerErrorMessage;
  displayName?: string;
};

export const TimePicker: TimePickerComponent = ({
  value,
  onChange,
  size = 'medium',
  minuteStep = 15,
  hourStep = 1,
  minTime,
  maxTime,
  isDisabled = false,
  isError = false,
  width,
  children,
}: TimePickerProps) => {
  const autoGeneratedId = useId();

  // 時 / 分の候補は value・props から純導出（隠れ state を持たない pure controlled）
  const hourOptions = useMemo(
    () => generateHourOptions(hourStep, minuteStep, minTime, maxTime),
    [hourStep, minuteStep, minTime, maxTime],
  );
  const minuteOptions = useMemo(
    () => generateMinuteOptions(minuteStep, value.hour, minTime, maxTime),
    [minuteStep, value.hour, minTime, maxTime],
  );

  // 表示中の選択オプションも value から純導出する
  const selectedHourOption = value.hour != null ? createHourOption(value.hour) : null;
  const selectedMinuteOption = value.minute != null ? createMinuteOption(value.minute) : null;

  const handleHourChange = (option: SelectOption | null) => {
    onChange({ hour: option != null ? Number(option.value) : null, minute: value.minute });
  };

  const handleMinuteChange = (option: SelectOption | null) => {
    onChange({ hour: value.hour, minute: option != null ? Number(option.value) : null });
  };

  // ErrorMessage の ID を収集し、各 Select トリガーの aria-describedby へ配線する
  const errorIds: string[] = [];
  const enhancedChildren = Children.map(children, (child) => {
    if (!isValidElement(child)) {
      return child;
    }

    if (child.type === TimePickerErrorMessage && isError) {
      const errorChild = child as ReactElement<TimePickerErrorMessageProps>;
      const assignedId = errorChild.props.id ?? `${autoGeneratedId}-error-${errorIds.length + 1}`;
      errorIds.push(assignedId);

      return cloneElement(errorChild, { id: assignedId });
    }

    return child;
  });

  // ErrorMessage がある場合のみ各 Select トリガーへ aria-describedby を配線する。
  // aria-invalid は Select が isError から内部導出するため、ここでは渡さない。
  const sharedAriaProps = errorIds.length > 0 ? { 'aria-describedby': errorIds.join(' ') } : {};

  // セパレータ（":"）はエラー / 無効でも色を変えず text02 のまま。タイポグラフィは size 連動
  const separatorClasses = clsx('text-text02', {
    'typography-label12regular': size === 'x-small',
    'typography-label14regular': size === 'small' || size === 'medium',
    'typography-label16regular': size === 'large',
  });

  const hasExplicitWidth = width != null;
  const selectWidth: CSSProperties['width'] = hasExplicitWidth ? '100%' : SELECT_WIDTH_BY_SIZE[size];
  const cellClasses = clsx('flex min-w-0', { 'flex-1': hasExplicitWidth });

  const contextValue = useMemo(() => ({ size, isError }), [size, isError]);

  const timeInputs = (
    <div className="flex items-center gap-2" style={{ width }}>
      <div className={cellClasses}>
        <Select
          size={size}
          width={selectWidth}
          placeholder={PLACEHOLDER}
          selectedOption={selectedHourOption}
          isDisabled={isDisabled}
          isError={isError}
          optionListMaxHeight={OPTION_LIST_MAX_HEIGHT}
          aria-label={HOUR_ARIA_LABEL}
          {...sharedAriaProps}
          onChange={handleHourChange}
        >
          {hourOptions.map((option) => (
            <Select.Option key={option.id} option={option} />
          ))}
        </Select>
      </div>
      <span className={separatorClasses}>:</span>
      <div className={cellClasses}>
        <Select
          size={size}
          width={selectWidth}
          placeholder={PLACEHOLDER}
          selectedOption={selectedMinuteOption}
          isDisabled={isDisabled}
          isError={isError}
          optionListMaxHeight={OPTION_LIST_MAX_HEIGHT}
          aria-label={MINUTE_ARIA_LABEL}
          {...sharedAriaProps}
          onChange={handleMinuteChange}
        >
          {minuteOptions.map((option) => (
            <Select.Option key={option.id} option={option} />
          ))}
        </Select>
      </div>
    </div>
  );

  const stackedChildren = enhancedChildren == null ? [] : Children.toArray(enhancedChildren);
  const hasMessageChildren = stackedChildren.length > 0;

  if (!hasMessageChildren) {
    return (
      <TimePickerCompoundContext.Provider value={contextValue}>
        <div className="flex flex-col">{timeInputs}</div>
      </TimePickerCompoundContext.Provider>
    );
  }

  return (
    <TimePickerCompoundContext.Provider value={contextValue}>
      <div className="flex flex-col gap-2">
        {timeInputs}
        {stackedChildren}
      </div>
    </TimePickerCompoundContext.Provider>
  );
};

TimePicker.ErrorMessage = TimePickerErrorMessage;
TimePicker.displayName = 'TimePicker';
