import { clsx } from 'clsx';
import type { ReactElement, ReactNode } from 'react';
import { Children, cloneElement, Fragment, isValidElement, useId, useMemo } from 'react';

import { Select } from '../select';
import type { SelectOption } from '../select/type';
import type { TimePickerSize } from './time-picker-context';
import { TimePickerCompoundContext } from './time-picker-context';
import type { TimePickerErrorMessageProps } from './time-picker-error-message';
import { TimePickerErrorMessage } from './time-picker-error-message';
import type { MinuteStep, TimeValue } from './time-picker-utils';
import {
  createHourOption,
  createMinuteOption,
  generateHourOptions,
  generateMinuteOptions,
  isTimeInRange,
} from './time-picker-utils';

/** サイズごとの各 Select の既定幅（px, Figma 実測値） */
const SELECT_WIDTH_BY_SIZE: Record<TimePickerSize, number> = {
  'x-small': 80,
  small: 80,
  medium: 80,
  large: 88,
};

/** 時・分 Select の未選択時プレースホルダー（内部固定） */
const PLACEHOLDER = '--';
/** 時 Select トリガーの aria-label（内部固定）。選択済みの場合は末尾に選択値が付く */
const HOUR_ARIA_LABEL = '時';
/** 分 Select トリガーの aria-label（内部固定）。選択済みの場合は末尾に選択値が付く */
const MINUTE_ARIA_LABEL = '分';

/**
 * Select トリガーのアクセシブルネームを生成する。
 * `aria-label` はトリガー内の可視テキスト（`09` 等）を上書きするため、選択済みの場合は
 * 可視値をそのまま含めて「時 09」のように現在値まで読み上げられるようにする。
 * 可視値（ゼロ埋め）を verbatim で含めることで WCAG 2.5.3（Label in Name）も満たす。
 */
const createTriggerAriaLabel = (baseLabel: string, selectedOption: SelectOption | null): string =>
  selectedOption != null ? `${baseLabel} ${selectedOption.label}` : baseLabel;
/**
 * 候補リストの最大高さ（内部固定）。時 Select（24 候補）が大きく出過ぎるのを防ぐ。
 * 候補 8 件分（264px）ちょうどにすると項目の切れ目と一致し、下にリストが続いていることが
 * わかりにくいため、あえて項目の途中で切れる 250px にしている
 */
const OPTION_LIST_MAX_HEIGHT = '250px';

export type TimePickerProps = {
  /** 選択時刻。`hour`・`minute` の両方が `null` の場合は未入力を表す */
  value: TimeValue;
  /** 時刻が変更されたときに呼び出されるコールバック関数。各 Select の変更ごとに新しい値を返す */
  onChange: (value: TimeValue) => void;
  /** コンポーネントのサイズ。内部の `Select` の size に 1:1 でマッピングされる @default 'medium' */
  size?: TimePickerSize;
  /** 分候補の刻み（60 の約数） @default 1 */
  minuteStep?: MinuteStep;
  /** 選択可能な最小時刻（`"HH:mm"`・inclusive）。範囲外の候補は非表示になる */
  minTime?: string;
  /** 選択可能な最大時刻（`"HH:mm"`・inclusive）。範囲外の候補は非表示になる */
  maxTime?: string;
  /** 無効状態かどうか @default false */
  isDisabled?: boolean;
  /** エラー状態かどうか。`true` の場合、両方の Select がエラー表示になる @default false */
  isError?: boolean;
  /** Compound Component（`TimePicker.ErrorMessage`） */
  children?: ReactNode;
};

type TimePickerComponent = ((props: TimePickerProps) => ReactElement) & {
  ErrorMessage: typeof TimePickerErrorMessage;
  displayName?: string;
};

export const TimePicker: TimePickerComponent = ({
  value,
  onChange,
  size = 'medium',
  minuteStep = 1,
  minTime,
  maxTime,
  isDisabled = false,
  isError = false,
  children,
}: TimePickerProps) => {
  const autoGeneratedId = useId();

  // 時 / 分の候補は value・props から純導出（隠れ state を持たない pure controlled）
  const hourOptions = useMemo(() => generateHourOptions(minuteStep, minTime, maxTime), [minuteStep, minTime, maxTime]);
  const minuteOptions = useMemo(
    () => generateMinuteOptions(minuteStep, value.hour, minTime, maxTime),
    [minuteStep, value.hour, minTime, maxTime],
  );

  // 表示中の選択オプションも value から純導出する
  const selectedHourOption = value.hour != null ? createHourOption(value.hour) : null;
  const selectedMinuteOption = value.minute != null ? createMinuteOption(value.minute) : null;

  const handleHourChange = (option: SelectOption | null) => {
    const nextHour = option != null ? Number(option.value) : null;
    // 選択済みの分が新しい時では範囲外になる場合、その分を未選択へ戻す。
    // 値を別の有効値へ丸めるのではなく「選べない組み合わせを未選択に戻す」だけなので、
    // 隠れ state を持たない pure controlled の原則は保たれる。
    const shouldResetMinute =
      nextHour != null && value.minute != null && !isTimeInRange(nextHour, value.minute, minTime, maxTime);

    onChange({ hour: nextHour, minute: shouldResetMinute ? null : value.minute });
  };

  const handleMinuteChange = (option: SelectOption | null) => {
    onChange({ hour: value.hour, minute: option != null ? Number(option.value) : null });
  };

  // ErrorMessage の ID を収集し、各 Select トリガーの aria-describedby へ配線する。
  // 配列やネストした Fragment 経由でも配線できるよう、Fragment は自身を保持したまま中身を再帰的に走査する
  // （Fragment ごと平坦化するとキーが重複し React が警告を出すため、cloneElement で構造を保つ）。
  // ただし `<div>` 等の任意の要素・コンポーネントで包んだ場合は配線されない（既知の制約）。
  const errorIds: string[] = [];
  const assignErrorIds = (nodes: ReactNode): ReactNode =>
    Children.map(nodes, (child) => {
      if (!isValidElement(child)) {
        return child;
      }

      if (child.type === Fragment) {
        const fragmentChild = child as ReactElement<{ children?: ReactNode }>;

        return cloneElement(fragmentChild, {}, assignErrorIds(fragmentChild.props.children));
      }

      if (child.type === TimePickerErrorMessage && isError) {
        const errorChild = child as ReactElement<TimePickerErrorMessageProps>;
        const assignedId = errorChild.props.id ?? `${autoGeneratedId}-error-${errorIds.length + 1}`;
        errorIds.push(assignedId);

        return cloneElement(errorChild, { id: assignedId });
      }

      return child;
    });

  const enhancedChildren = assignErrorIds(children);

  // ErrorMessage がある場合のみ各 Select トリガーへ aria-describedby を配線する。
  // aria-invalid は Select が isError から内部導出するため、ここでは渡さない。
  const sharedAriaProps = errorIds.length > 0 ? { 'aria-describedby': errorIds.join(' ') } : {};

  // セパレータ（":"）はエラー / 無効でも色を変えず text02 のまま。タイポグラフィは size 連動
  const separatorClasses = clsx('text-text02', {
    'typography-label12regular': size === 'x-small',
    'typography-label14regular': size === 'small' || size === 'medium',
    'typography-label16regular': size === 'large',
  });

  const selectWidth = SELECT_WIDTH_BY_SIZE[size];

  const contextValue = useMemo(() => ({ size, isError }), [size, isError]);

  const timeInputs = (
    <div className="flex items-center gap-2">
      <Select
        size={size}
        width={selectWidth}
        placeholder={PLACEHOLDER}
        selectedOption={selectedHourOption}
        isDisabled={isDisabled}
        isError={isError}
        optionListMaxHeight={OPTION_LIST_MAX_HEIGHT}
        aria-label={createTriggerAriaLabel(HOUR_ARIA_LABEL, selectedHourOption)}
        {...sharedAriaProps}
        onChange={handleHourChange}
      >
        {hourOptions.map((option) => (
          <Select.Option key={option.id} option={option} />
        ))}
      </Select>
      <span className={separatorClasses}>:</span>
      <Select
        size={size}
        width={selectWidth}
        placeholder={PLACEHOLDER}
        selectedOption={selectedMinuteOption}
        isDisabled={isDisabled}
        isError={isError}
        optionListMaxHeight={OPTION_LIST_MAX_HEIGHT}
        aria-label={createTriggerAriaLabel(MINUTE_ARIA_LABEL, selectedMinuteOption)}
        {...sharedAriaProps}
        onChange={handleMinuteChange}
      >
        {minuteOptions.map((option) => (
          <Select.Option key={option.id} option={option} />
        ))}
      </Select>
    </div>
  );

  const stackedChildren = enhancedChildren == null ? [] : Children.toArray(enhancedChildren);
  const hasMessageChildren = stackedChildren.length > 0;

  if (!hasMessageChildren) {
    return (
      <TimePickerCompoundContext.Provider value={contextValue}>
        <div className="flex flex-col">{timeInputs}</div>
      </TimePickerCompoundContext.Provider>
    );
  }

  return (
    <TimePickerCompoundContext.Provider value={contextValue}>
      <div className="flex flex-col gap-2">
        {timeInputs}
        {stackedChildren}
      </div>
    </TimePickerCompoundContext.Provider>
  );
};

TimePicker.ErrorMessage = TimePickerErrorMessage;
TimePicker.displayName = 'TimePicker';
