export type LightColor =
  | '#F4BFCD'
  | '#CCF4E1'
  | '#FFF4BA'
  | '#FDDADA'
  | '#FBDEF5'
  | '#EFDCF7'
  | '#DBF0F7'
  | '#DFE8FB'
  | '#D8EFFC'
  | '#D8EFFC'
  | '#DCF7DC'
  | '#FCEFB6'
  | '#FDE8C0'
  | '#B9D8F7'
  | 'UiBackgroundGray';
