export const userColors = [
  'bg-user-red',
  'bg-user-pink',
  'bg-user-purple',
  'bg-user-turquoise',
  'bg-user-royalBlue',
  'bg-user-blue',
  'bg-user-aquamarine',
  'bg-user-yellowGreen',
  'bg-user-yellow',
  'bg-user-orange',
] as const;

export const buttonColors = {
  fill: {
    base: 'border border-interactive01 bg-interactive01 text-textOnColor fill-textOnColor',
    hover: 'hover:bg-hover01 hover:border-hover01',
    active: 'active:bg-active01 active:border-active01',
    disabled: 'disabled:bg-disabled01 disabled:border-disabled01',
    selected: 'border border-transparent bg-selectedUi text-interactive01 fill-interactive01',
  },
  fillDanger: {
    base: 'border border-supportDanger bg-supportDanger text-textOnColor fill-textOnColor',
    hover: 'hover:bg-hoverDanger hover:border-hoverDanger',
    active: 'active:bg-activeDanger active:border-activeDanger',
    disabled: 'disabled:bg-disabled01 disabled:border-disabled01',
    selected: 'border border-transparent bg-supportDangerLight text-supportDanger fill-supportDanger',
  },
  outline: {
    base: 'border border-uiBorder02 text-interactive02 fill-interactive02',
    hover: 'hover:bg-hover02',
    active: 'active:bg-active02',
    disabled: 'disabled:border-uiBorder01 disabled:text-disabled01 disabled:fill-disabled01',
    selected: 'border border-interactive01 bg-selectedUi text-interactive01 fill-interactive01',
  },
  text: {
    base: 'border border-transparent text-interactive02 fill-interactive02',
    hover: 'hover:bg-hover02 hover:border-hover02',
    active: 'active:bg-active02 active:border-active02',
    disabled: 'disabled:text-disabled01 disabled:fill-disabled01',
    selected: 'border border-transparent bg-selectedUi text-interactive01 fill-interactive01',
  },
} as const;

export const iconColors = {
  icon01: 'fill-icon01',
  icon01Dark: 'fill-icon01Dark',
  icon02: 'fill-icon02',
  icon02Dark: 'fill-icon02Dark',
  icon03: 'fill-icon03',
  icon03Dark: 'fill-icon03Dark',
  iconOnColor: 'fill-iconOnColor',

  black: 'fill-black',
  white: 'fill-white',
  blue10: 'fill-blue-blue10',
  blue20: 'fill-blue-blue20',
  blue30: 'fill-blue-blue30',
  blue40: 'fill-blue-blue40',
  blue50: 'fill-blue-blue50',
  blue60: 'fill-blue-blue60',
  blue70: 'fill-blue-blue70',
  blue80: 'fill-blue-blue80',
  blue90: 'fill-blue-blue90',
  blue100: 'fill-blue-blue100',
  gray10: 'fill-gray-gray10',
  gray20: 'fill-gray-gray20',
  gray30: 'fill-gray-gray30',
  gray40: 'fill-gray-gray40',
  gray50: 'fill-gray-gray50',
  gray60: 'fill-gray-gray60',
  gray70: 'fill-gray-gray70',
  gray80: 'fill-gray-gray80',
  gray90: 'fill-gray-gray90',
  gray100: 'fill-gray-gray100',
  red10: 'fill-red-red10',
  red20: 'fill-red-red20',
  red30: 'fill-red-red30',
  red40: 'fill-red-red40',
  red50: 'fill-red-red50',
  red60: 'fill-red-red60',
  red70: 'fill-red-red70',
  red80: 'fill-red-red80',
  red90: 'fill-red-red90',
  red100: 'fill-red-red100',
  yellow10: 'fill-yellow-yellow10',
  yellow20: 'fill-yellow-yellow20',
  yellow30: 'fill-yellow-yellow30',
  yellow40: 'fill-yellow-yellow40',
  yellow50: 'fill-yellow-yellow50',
  yellow60: 'fill-yellow-yellow60',
  yellow70: 'fill-yellow-yellow70',
  yellow80: 'fill-yellow-yellow80',
  yellow90: 'fill-yellow-yellow90',
  yellow100: 'fill-yellow-yellow100',
  green10: 'fill-green-green10',
  green20: 'fill-green-green20',
  green30: 'fill-green-green30',
  green40: 'fill-green-green40',
  green50: 'fill-green-green50',
  green60: 'fill-green-green60',
  green70: 'fill-green-green70',
  green80: 'fill-green-green80',
  green90: 'fill-green-green90',
  green100: 'fill-green-green100',
  purple10: 'fill-purple-purple10',
  purple20: 'fill-purple-purple20',
  purple30: 'fill-purple-purple30',
  purple40: 'fill-purple-purple40',
  purple50: 'fill-purple-purple50',
  purple60: 'fill-purple-purple60',
  purple70: 'fill-purple-purple70',
  purple80: 'fill-purple-purple80',
  purple90: 'fill-purple-purple90',
  purple100: 'fill-purple-purple100',
  blueGreen10: 'fill-blueGreen-blueGreen10',
  blueGreen20: 'fill-blueGreen-blueGreen20',
  blueGreen30: 'fill-blueGreen-blueGreen30',
  blueGreen40: 'fill-blueGreen-blueGreen40',
  blueGreen50: 'fill-blueGreen-blueGreen50',
  blueGreen60: 'fill-blueGreen-blueGreen60',
  blueGreen70: 'fill-blueGreen-blueGreen70',
  blueGreen80: 'fill-blueGreen-blueGreen80',
  blueGreen90: 'fill-blueGreen-blueGreen90',
  blueGreen100: 'fill-blueGreen-blueGreen100',
} as const;

export const tagColors = {
  supportError: 'text-textOnColor bg-supportError',
  supportSuccess: 'text-textOnColor bg-supportSuccess',
  supportWarning: 'text-textOnColor bg-supportWarning',
  supportDanger: 'text-textOnColor bg-supportDanger',
  userRed: 'text-textOnColor bg-user-red',
  userPink: 'text-textOnColor bg-user-pink',
  userPurple: 'text-textOnColor bg-user-purple',
  userTurquoise: 'text-textOnColor bg-user-turquoise',
  userRoyalBlue: 'text-textOnColor bg-user-royalBlue',
  userBlue: 'text-textOnColor bg-user-blue',
  userAquamarine: 'text-textOnColor bg-user-aquamarine',
  userYellowGreen: 'text-textOnColor bg-user-yellowGreen',
  userYellow: 'text-textOnColor bg-user-yellow',
  userOrange: 'text-textOnColor bg-user-orange',
  default: 'text-textOnColor bg-supportInfo',
  gray: 'text-text02 bg-gray-gray10',
} as const;

export const tagLightColors = {
  supportError: 'text-text01 bg-supportErrorLight',
  supportSuccess: 'text-text01 bg-supportSuccessLight',
  supportWarning: 'text-text01 bg-supportWarningLight',
  supportDanger: 'text-text01 bg-supportDangerLight',
  userRed: 'text-text01 bg-user-redLight',
  userPink: 'text-text01 bg-user-pinkLight',
  userPurple: 'text-text01 bg-user-purpleLight',
  userTurquoise: 'text-text01 bg-user-turquoiseLight',
  userRoyalBlue: 'text-text01 bg-user-royalBlueLight',
  userBlue: 'text-text01 bg-user-blueLight',
  userAquamarine: 'text-text01 bg-user-aquamarineLight',
  userYellowGreen: 'text-text01 bg-user-yellowGreenLight',
  userYellow: 'text-text01 bg-user-yellowLight',
  userOrange: 'text-text01 bg-user-orangeLight',
  default: 'text-text01 bg-supportInfoLight',
  gray: 'text-text01 bg-gray-gray10',
} as const;
