export const typography = {
  heading: {
    h1: 'font-bold leading-0 text-7 tracking-normal no-underline',
    h2: 'font-bold leading-1 text-6 tracking-normal no-underline',
    h3: 'font-bold leading-2 text-5 tracking-normal no-underline',
    h4: 'font-bold leading-3 text-4 tracking-normal no-underline',
    h5: 'font-bold leading-4 text-3 tracking-normal no-underline',
  },
  body: {
    body16bold: 'font-bold leading-5 text-4 tracking-normal no-underline',
    body16regular: 'font-normal leading-5 text-4 tracking-normal no-underline',
    body14bold: 'font-bold leading-4 text-3 tracking-normal no-underline',
    body14regular: 'font-normal leading-4 text-3 tracking-normal no-underline',
    body13bold: 'font-bold leading-5 text-2 tracking-normal no-underline',
    body13regular: 'font-normal leading-5 text-2 tracking-normal no-underline',
    body12bold: 'font-bold leading-1 text-1 tracking-normal no-underline',
    body12regular: 'font-normal leading-1 text-1 tracking-normal no-underline',
  },
  label: {
    label16bold: 'font-bold leading-6 text-4 tracking-normal no-underline',
    label16regular: 'font-normal leading-6 text-4 tracking-normal no-underline',
    label14bold: 'font-bold leading-6 text-3 tracking-normal no-underline',
    label14regular: 'font-normal leading-6 text-3 tracking-normal no-underline',
    label13bold: 'font-bold leading-6 text-2 tracking-normal no-underline',
    label13regular: 'font-normal leading-6 text-2 tracking-normal no-underline',
    label12bold: 'font-bold leading-6 text-1 tracking-normal no-underline',
    label12regular: 'font-normal leading-6 text-1 tracking-normal no-underline',
    label11bold: 'font-bold leading-6 text-0 tracking-normal no-underline',
    label11regular: 'font-normal leading-6 text-0 tracking-normal no-underline',
  },
} as const;
