name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Build
        run: pnpm build:all

      - name: TypeScript type check
        run: pnpm type-check

  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Build
        run: pnpm build:all

      - name: Lint and filename check
        run: pnpm lint

  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Build
        run: pnpm build:all

      - name: Test
        run: pnpm test:ci
